name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        esy: [0.5.0, 0.5.8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install esy and run test
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add esy $GITHUB_WORKSPACE
          asdf install esy ${{ matrix.esy }}
          asdf global esy ${{ matrix.esy }}
          esy --version

  format:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .
